data:
  
  smard_consumption_month: "../data/raw/smard_consumption_month.csv"
  smard_generation_month: "../data/raw/smard_generation_month.csv"
  smard_clean: "../data/cleaned/smard_clean.csv"
  average_prices: "../data/raw/average_electricity_price_household.csv"
  aveage_prices_clean: "../data/cleaned/average_prices_clean.csv"